### ISSUE TITLE
Thanks for this updated version!

### ISSUE THREAD

**Issue by agibson2** [nickjeffrey/check_snmp_storage#1]
I was using a version 1.3.3 that was working fine in RHEL 7, but after updating to RHEL 9, the disks were coming back in some kind of cycling order so the stats that were getting sent to pnp4nagios was all mixed up between the disks.  I found your version that has the sort for the keys that fixes it.

Thank you.  Thank you.  Thank you.  Life saver :).

If anyone is using check_snmp_storage.pl version 1.3.3 and switches to RHEL 9, This version works properly with the new OS.  I assume it is some change in perl or snmp library or something that caused it?

Yea... this isn't a bug.  Maybe you will forgive me :).

**Comment by nickjeffrey** [comment]
Glad to help
